### ISSUE TITLE
Feature: Users can see the home page

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/colosseum#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the home page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user first open the website, they are able to view the home landing page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-28 at 9 15 45 PM](https://user-images.githubusercontent.com/88172055/187121961-11656b87-0a49-4704-bf30-84f341913c41.png)
![Screen Shot 2022-08-28 at 9 16 00 PM](https://user-images.githubusercontent.com/88172055/187121971-8a4d6406-9cc5-4325-8fef-d1d15862b158.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a server directory containing index.js
- [x] Set up initial requirements for middlewares and express

### ⚡ Client

- [x] Create HTML skeleton with applicable scripts and links
- [x] Create header
- [x] Create footer
- [x] Create app drawer and nav links
- [x] Create CSS for visual configuration of HTML

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
