### ISSUE TITLE
Feature: User can add a review

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/colosseum#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account and login
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is able to navigate through buttons and see a sign-up/login page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Set up GET route to read reviews for each individual gym
- [x] Set up POST route to receive requests for gym reviews before inserting into the database
- [x] Set up PATCH route for a user to update their review

###  📖 Database
- [x] Rework schema to include a "review" table and link it to "gyms" and "users" tables
- [x] Update initial database seed to include reviews for premade gyms

### ⚡ Client

- [x] Create a Review Card component
- [x] Update Gym page to have a reviews section 
- [x] Create a modal for adding reviews

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
