### ISSUE TITLE
Feature: User can see location of gym on a map

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/colosseum#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see location of gym on a map
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is able see an accurate map for the gym when they open up a listing
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Adjust the POST route for gym creation to handle geocoding addresses and inserting them into the database
- [x] Adjust the PATCH route for a user to update their gym location and geocode the new location before updating the database

###  📖 Database
- [x] Rework schema to include a "geodata" column for the "gyms" table
- [x] Update initial database seed to include geodata for premade gyms

### ⚡ Client

- [x] Update Gym page to have a map component
- [x] Have the map display a marker with the exact location 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
