### ISSUE TITLE
Feature: User can filter and display gyms by type

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/colosseum#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter and display gyms by its type
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to choose what what type of gyms that they're looking for in a filter form at the top of the listing page and when the form is submitted, the listings will only show the gyms of that type.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update Listings page to have a filter form component
- [x] Have the Listings component re-render after the filter component user applies the filter

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Jimmy-Vu** [comment]
Note: This implementation might be better/faster if the filtering is for the local state instead of sending a GET request to the server to query the database as the local state should already contain the gym listings when the listings are rendered for the first time. Further research/thinking should be done.
