### ISSUE TITLE
User can create a gym listing

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/colosseum#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a gym listing to the web application
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can navigate to an "Add Gym" page and submit a form for a new gym creation.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Set up a POST route to receive requests to create more listings
- [x] Set up middleware to handle image uploads and send to hosting server
- [x] Implement safeguards for post method

### ⚡ Client

- [x] Create an "Add Arena Page"

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
