### ISSUE TITLE
Feature: User can login into their account

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/colosseum#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account and login
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is able to navigate through buttons and see a sign-up/login page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Set up POST route to receive requests to account creation and hash passwords before inserting into the database
- [x] Set up POST route to handle requests for logins and provide password verification
- [x] Set up POST route for a demo user

###  📖 Database
- [x] Rework schema to include a "users" table and link gym rows to corresponding users
- [x] Update initial database seed to include a demo user

### ⚡ Client

- [x] Create "Sign Up/Login" components
- [x] Set up conditional rendering for authorization page
- [x] Introduce redux for managing global app and user states
- [x] Add a "My Account" page to provide quick visual access to a user's created gym

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
